### ISSUE TITLE
Pkgdown deployment failing on travis

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#305]
This is causing it to appear in the Travis dashboard as if the entire build failed.
```
Installing deploy dependencies
Fetching dpl-script-1.10.8.gem
Successfully installed dpl-script-1.10.8
Parsing documentation for dpl-script-1.10.8
Installing ri documentation for dpl-script-1.10.8
Done installing documentation for dpl-script after 0 seconds
1 gem installed
dpl.2
Preparing deploy
dpl.3
Deploying application
Error: No deploy key found, please setup with `travis::use_travis_deploy()`
Execution halted
Script failed with status 1
failed to deploy
```
It looks like a configuration problem, but I'm not entirely sure where and how the deploy key is supposed to be installed.

**Comment by ashiklom** [comment]
So I can't actually do anything about this because I don't have admin privileges on the Hector repo, which are required to create the deploy key. If you can give me admin privileges temporarily, it'll only take about a few minutes for me to resolve, and then you can revoke the privileges once I'm done.

**Comment by bpbond** [comment]
Done! Thanks @ashiklom

**Comment by ashiklom** [comment]
@bpbond "Done" as in you have me permissions, or "done" as in you did the `travis::use_travis_deploy()` yourself? I'm asking because I still don't have the right permissions to fix this:

```
Error: Must have role admin to add deploy key to repo JGCRI/hector, not write
```

My understanding of GitHub permissions is hazy, but I think this means I would have to be made an "Owner" of the JGCRI organization for this to work, which is overkill and responsibility I don't want to have, even temporarily (in case it's irreversible or something).

If `travis` fails to install for some reason, you can also do these steps manually. Based on the source for [`travis::use_pkg_deploy()`](https://github.com/ropenscilabs/travis/blob/master/R/setup.R) and [`pkgdown::deploy_site_github()`](https://github.com/r-lib/pkgdown/blob/master/R/deploy-site.R), I think they are as follows:

1. On your local machine, create an OpenSSL public-private key pair (shell command `ssh-keygen`, or, with R, `openssl::rsa_keygen()`).
2. `pkgdown` requires the private key to be base64-encoded. I'm not sure how to do this with shell commands, but with the R `openssl` package, I think something like the following should work:

    ```r
    private_key <- paste(readLines("~/.ssh/<private_key_file>"), collapse = "\n")
    openssl::base64_encode(charToRaw(private_key))
    ```

    You will need this encoded output for step 4.

3. In the JGCRI/Hector GitHub repo, go to _Settings_, _Deploy keys_ and add the _public_ key there. I'm pretty sure the key will need "Write access".
4. In the JGCRI/Hector _Travis_ repo (https://travis-ci.org/JGCRI/hector), go to _More options_, _Settings_, and under _Environment variables_, "add" a new variable called `id_rsa` (all lowercase) with the encoded private key from step 2.

**Comment by bpbond** [comment]
Ah, that was done in the sense of being a Hector admin. OK, hang on.

**Comment by ashiklom** [comment]
I think this is fixed. [Here's](https://travis-ci.org/JGCRI/hector/jobs/528839857) a successful Travis build off `master`, and [here's](http://jgcri.github.io/hector/) the rendered package website.

**Comment by bpbond** [comment]
👏  thanks @ashiklom - looks great.
